### ISSUE TITLE
Lines being deleted ununexpectedly when Isort insert new lines

### ISSUE THREAD

**Issue by kazhala** [brentyi/isort.vim#2]
Hi @brentyi,

Amazing plugin, loving the async implementation, thank you for the hard work.

I was playing around the plugin and discovered this behaviour. Please see the gif below.

![bug](https://user-images.githubusercontent.com/43941510/103977137-aea29180-51cc-11eb-8e19-f598ab9544f1.gif)

editor: Neovim 0.4.4
isort: v5.7.0

Thanks,
Kevin

**Comment by brentyi** [comment]
Hi @kazhala --

Thanks for the report!

This is most definitely this (hacky) condition kicking in, which ignores the last line we get in Neovim:
https://github.com/brentyi/isort.vim/blob/ce96be70263fa10ced845a164666fc990e86ae22/autoload/isort.vim#L2-L8

I was able to reproduce your issue but not able to reproduce the failure that motivated the hack (maybe a bug in an old version of Neovim?), so I just removed the condition altogether.

Can you give that a try?

**Comment by kazhala** [comment]
Hi @brentyi,

Appreciate the quick fix, works like a charm now!

Thanks,
Kevin
