### ISSUE TITLE
Error when running as autocmd

### ISSUE THREAD

**Issue by reinhardt** [brentyi/isort.vim#3]
I have the following in my vimrc:

```
autocmd BufWritePre *.py execute ':Isort'
```

When saving multiple files with `:wa` I get the error

```
Error detected while processing function <lambda>16[1]..<SNR>116_IsortDoneCallback:
line    1:
E108: No such variable: "s:job"
```

**Comment by brentyi** [comment]
Thanks for the report! Disabling the async buffer updates should fix this, I just pushed an option for this.

Can you update the plugin and try this line instead?
```
autocmd BufWritePre *.py call isort#Isort(0, line('$'), v:null, v:false)
```

**Comment by reinhardt** [comment]
Indeed, that does the trick! Thank you very much! :sparkler:
