### ISSUE TITLE
Isort warning inserted into buffer

### ISSUE THREAD

**Issue by reinhardt** [brentyi/isort.vim#4]
This is a followup to #3.

When I call `isort#Isort(0, line('$'), v:null, v:false)` (either via autocmd or manually in command mode) I get lines like these inserted into the buffer:

```
[...]/lib/python3.8/site-packages/isort/settings.py:495: UserWarning: W0503: Deprecated config options were used: not_skip.Please see the 5.0.0 upgrade guide: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html
  warn(
```

I'm using isort version 5.10.1.

Also, running `:Isort` in command mode gives me `isort#Isort got the wrong number of arguments!`. (Would you like a separate ticket for that?)

**Comment by brentyi** [comment]
@reinhardt thanks for flagging this as well! These issues should both be fixed now, please follow up if you're still having issues.
